language: node_js
node_js:
- "8"

jobs:
  include:
    - stage: Produce coverage
    node_js: node_js
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage